// https://thoughtcatalog.com/january-nelson/2018/06/chicken-puns/

export var ChickenPuns: string[] = [
"What do you get when you cross a chicken and a four-leaf clover?\nThe Cluck o’the Irish!",
"What’s a hen’s favorite type of movie?\nA chick flick.",
"How do baby chickens dance?\nChick-to-chick.",
"What do you get when you cross a chicken with a bell?\nAn alarm cluck.",
"Which chicken is at the top of the pecking order?\nAttila the Hen.",
"Why do chickens lay eggs?\nBecause if they dropped them, they’d break.",
"What do you call a chicken that crosses the road?\nPoultry in motion.",
"Why is it easy for chicks to talk?\nBecause talk is cheep.",
"What happens when a hen eats gunpowder?\nShe lays hand gren-eggs.",
"What do you get when you cross a ghost with a chicken?\nA poultry-geist.",
"Why did the chicken cross the playground?\nHe wanted to get to the other slide.",
"How do you know if it’s too hot in the chicken barn?\nThe chickens are laying hard-cooked eggs.",
"What do chickens grow on?\nEggplants.",
"What does a chicken need to lay an egg every day?\nHen-durance.",
"What do chicken families do on Saturday afternoon?\nThey go on peck-nics.",
"What kind of chicken grows on a tree?\nPoultry.",
"What happened to the baby chicken that misbehaved at school?\nIt was egg-spelled.",
"The chicken farmer died under mysterious circumstances.\nThe police suspect fowl play.",
"I have no idea how to raise chickens.\nI think I’ll just wing it.",
"I ate an omelette for breakfast…\nbut I’m still feeling peckish.",
"What do you call a chicken that crosses the road, rolls in the dirt, crosses the road again, and then rolls in the dirt again?\nA dirty double-crossing chicken.",
"Why did the chicken cross the road halfway?\nShe wanted to lay it on the line.",
"What do you call the door to a chicken barn?\nThe hen-trance.",
"What did the baby chicken say when he saw his mother sitting on an orange?\nDad, look what marma-laid!",
"Why can’t a rooster ever get rich?\nBecause he works for chicken feed.",
"What do chickens call school tests?\nEggs-aminations.",
"What do you call a crazy chicken?\nA cuckoo cluck.",
"What do you get when a chicken lays an egg on top of a barn?\nAn eggroll.",
"What do chickens serve at birthday parties?\nCoop-cakes.",
"Why does a chicken coop have two doors?\nBecause if had four doors it would be a chicken sedan.",
"Which dance will a chicken not do?\nThe foxtrot.",
"What do you call a bird that's afraid to fly?\nChicken.",
"What do you get if you feed gunpowder to a chicken?\nAn egg-splosion.",
"How long do chickens work?\nAround the cluck",
"Which day of the week do chickens hate most?\nFry-day",
"Why did the chick disappoint his mother?\nHe wasn’t what he was cracked up to be.",
"Is chicken soup good for your health?\nNot if you’re the chicken.",
"When do chickens go to bed?\nHalf past hen!",
"When the farmer died, all his chickens were sold to the highest bidder.\nThey would have preferred to stay on the farm, but auctions speak louder than birds.",
"Why did the chicken go to KFC?\nHe wanted to see a chicken strip.",
"Why did the chicken join a band?\nBecause it already had drumsticks.",
"What do chickens study in school?\nEggonomics.",
"Why did the chicken cross the basketball court?\nHe heard the referee calling fowls.",
"Did you hear about the chicken who could only lay eggs in the winter?\nShe was no spring chicken.",
"How does a chicken mail a letter to her friend?\nIn a HEN-velope!",
"What do you call a group of chickens clucking in unison?\nA Hensemble.",
"Why don’t chickens wear pants?\nThere peckers are on their face.",
"Why did the t-rex cross the road?\nBecause the chicken hadn’t evolved yet.",
"What did one chicken say to the other after they walked through poison ivy?\n“You scratch my beak and I’ll scratch yours!”",
"How did the headless chicken cross the road?\nIn a KFC bucket."
];